/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedOfficialRouteImport } from './routes/_protected/official'
import { Route as ProtectedCitizenRouteImport } from './routes/_protected/citizen'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ProtectedOfficialResidentsRouteImport } from './routes/_protected/official/residents'
import { Route as ProtectedOfficialReportsRouteImport } from './routes/_protected/official/reports'
import { Route as ProtectedOfficialDocumentsRouteImport } from './routes/_protected/official/documents'
import { Route as ProtectedOfficialDashboardRouteImport } from './routes/_protected/official/dashboard'
import { Route as ProtectedOfficialComplaintsRouteImport } from './routes/_protected/official/complaints'
import { Route as ProtectedCitizenServicesRouteImport } from './routes/_protected/citizen/services'
import { Route as ProtectedCitizenProfileRouteImport } from './routes/_protected/citizen/profile'
import { Route as ProtectedCitizenMapRouteImport } from './routes/_protected/citizen/map'
import { Route as ProtectedCitizenDocumentsNewRouteImport } from './routes/_protected/citizen/documents-new'
import { Route as ProtectedCitizenDocumentsRouteImport } from './routes/_protected/citizen/documents'
import { Route as ProtectedCitizenDashboardRouteImport } from './routes/_protected/citizen/dashboard'
import { Route as ProtectedCitizenComplaintsNewRouteImport } from './routes/_protected/citizen/complaints-new'
import { Route as ProtectedCitizenComplaintsRouteImport } from './routes/_protected/citizen/complaints'
import { Route as ProtectedCitizenAnnouncementsDetailedRouteImport } from './routes/_protected/citizen/announcements-detailed'
import { Route as ProtectedCitizenAnnouncementsRouteImport } from './routes/_protected/citizen/announcements'
import { Route as ProtectedAdminUsersRouteImport } from './routes/_protected/admin/users'
import { Route as ProtectedAdminSettingsRouteImport } from './routes/_protected/admin/settings'
import { Route as ProtectedAdminRolesRouteImport } from './routes/_protected/admin/roles'
import { Route as ProtectedAdminResidentsRouteImport } from './routes/_protected/admin/residents'
import { Route as ProtectedAdminDashboardRouteImport } from './routes/_protected/admin/dashboard'
import { Route as ProtectedAdminComplaintsRouteImport } from './routes/_protected/admin/complaints'
import { Route as ProtectedAdminCertificatesRouteImport } from './routes/_protected/admin/certificates'
import { Route as ProtectedAdminAnnouncementsRouteImport } from './routes/_protected/admin/announcements'
import { Route as ProtectedAdminAnalyticsRouteImport } from './routes/_protected/admin/analytics'
import { Route as ProtectedAdminActivityLogsRouteImport } from './routes/_protected/admin/activity-logs'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOfficialRoute = ProtectedOfficialRouteImport.update({
  id: '/official',
  path: '/official',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCitizenRoute = ProtectedCitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOfficialResidentsRoute =
  ProtectedOfficialResidentsRouteImport.update({
    id: '/residents',
    path: '/residents',
    getParentRoute: () => ProtectedOfficialRoute,
  } as any)
const ProtectedOfficialReportsRoute =
  ProtectedOfficialReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => ProtectedOfficialRoute,
  } as any)
const ProtectedOfficialDocumentsRoute =
  ProtectedOfficialDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ProtectedOfficialRoute,
  } as any)
const ProtectedOfficialDashboardRoute =
  ProtectedOfficialDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedOfficialRoute,
  } as any)
const ProtectedOfficialComplaintsRoute =
  ProtectedOfficialComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => ProtectedOfficialRoute,
  } as any)
const ProtectedCitizenServicesRoute =
  ProtectedCitizenServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => ProtectedCitizenRoute,
  } as any)
const ProtectedCitizenProfileRoute = ProtectedCitizenProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedCitizenRoute,
} as any)
const ProtectedCitizenMapRoute = ProtectedCitizenMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => ProtectedCitizenRoute,
} as any)
const ProtectedCitizenDocumentsNewRoute =
  ProtectedCitizenDocumentsNewRouteImport.update({
    id: '/documents-new',
    path: '/documents-new',
    getParentRoute: () => ProtectedCitizenRoute,
  } as any)
const ProtectedCitizenDocumentsRoute =
  ProtectedCitizenDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ProtectedCitizenRoute,
  } as any)
const ProtectedCitizenDashboardRoute =
  ProtectedCitizenDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedCitizenRoute,
  } as any)
const ProtectedCitizenComplaintsNewRoute =
  ProtectedCitizenComplaintsNewRouteImport.update({
    id: '/complaints-new',
    path: '/complaints-new',
    getParentRoute: () => ProtectedCitizenRoute,
  } as any)
const ProtectedCitizenComplaintsRoute =
  ProtectedCitizenComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => ProtectedCitizenRoute,
  } as any)
const ProtectedCitizenAnnouncementsDetailedRoute =
  ProtectedCitizenAnnouncementsDetailedRouteImport.update({
    id: '/announcements-detailed',
    path: '/announcements-detailed',
    getParentRoute: () => ProtectedCitizenRoute,
  } as any)
const ProtectedCitizenAnnouncementsRoute =
  ProtectedCitizenAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => ProtectedCitizenRoute,
  } as any)
const ProtectedAdminUsersRoute = ProtectedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminSettingsRoute = ProtectedAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminRolesRoute = ProtectedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminResidentsRoute = ProtectedAdminResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminDashboardRoute = ProtectedAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminComplaintsRoute =
  ProtectedAdminComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminCertificatesRoute =
  ProtectedAdminCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminAnnouncementsRoute =
  ProtectedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminAnalyticsRoute = ProtectedAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminActivityLogsRoute =
  ProtectedAdminActivityLogsRouteImport.update({
    id: '/activity-logs',
    path: '/activity-logs',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/citizen': typeof ProtectedCitizenRouteWithChildren
  '/official': typeof ProtectedOfficialRouteWithChildren
  '/settings': typeof ProtectedSettingsRoute
  '/admin/activity-logs': typeof ProtectedAdminActivityLogsRoute
  '/admin/analytics': typeof ProtectedAdminAnalyticsRoute
  '/admin/announcements': typeof ProtectedAdminAnnouncementsRoute
  '/admin/certificates': typeof ProtectedAdminCertificatesRoute
  '/admin/complaints': typeof ProtectedAdminComplaintsRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/admin/residents': typeof ProtectedAdminResidentsRoute
  '/admin/roles': typeof ProtectedAdminRolesRoute
  '/admin/settings': typeof ProtectedAdminSettingsRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/citizen/announcements': typeof ProtectedCitizenAnnouncementsRoute
  '/citizen/announcements-detailed': typeof ProtectedCitizenAnnouncementsDetailedRoute
  '/citizen/complaints': typeof ProtectedCitizenComplaintsRoute
  '/citizen/complaints-new': typeof ProtectedCitizenComplaintsNewRoute
  '/citizen/dashboard': typeof ProtectedCitizenDashboardRoute
  '/citizen/documents': typeof ProtectedCitizenDocumentsRoute
  '/citizen/documents-new': typeof ProtectedCitizenDocumentsNewRoute
  '/citizen/map': typeof ProtectedCitizenMapRoute
  '/citizen/profile': typeof ProtectedCitizenProfileRoute
  '/citizen/services': typeof ProtectedCitizenServicesRoute
  '/official/complaints': typeof ProtectedOfficialComplaintsRoute
  '/official/dashboard': typeof ProtectedOfficialDashboardRoute
  '/official/documents': typeof ProtectedOfficialDocumentsRoute
  '/official/reports': typeof ProtectedOfficialReportsRoute
  '/official/residents': typeof ProtectedOfficialResidentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/citizen': typeof ProtectedCitizenRouteWithChildren
  '/official': typeof ProtectedOfficialRouteWithChildren
  '/settings': typeof ProtectedSettingsRoute
  '/admin/activity-logs': typeof ProtectedAdminActivityLogsRoute
  '/admin/analytics': typeof ProtectedAdminAnalyticsRoute
  '/admin/announcements': typeof ProtectedAdminAnnouncementsRoute
  '/admin/certificates': typeof ProtectedAdminCertificatesRoute
  '/admin/complaints': typeof ProtectedAdminComplaintsRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/admin/residents': typeof ProtectedAdminResidentsRoute
  '/admin/roles': typeof ProtectedAdminRolesRoute
  '/admin/settings': typeof ProtectedAdminSettingsRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/citizen/announcements': typeof ProtectedCitizenAnnouncementsRoute
  '/citizen/announcements-detailed': typeof ProtectedCitizenAnnouncementsDetailedRoute
  '/citizen/complaints': typeof ProtectedCitizenComplaintsRoute
  '/citizen/complaints-new': typeof ProtectedCitizenComplaintsNewRoute
  '/citizen/dashboard': typeof ProtectedCitizenDashboardRoute
  '/citizen/documents': typeof ProtectedCitizenDocumentsRoute
  '/citizen/documents-new': typeof ProtectedCitizenDocumentsNewRoute
  '/citizen/map': typeof ProtectedCitizenMapRoute
  '/citizen/profile': typeof ProtectedCitizenProfileRoute
  '/citizen/services': typeof ProtectedCitizenServicesRoute
  '/official/complaints': typeof ProtectedOfficialComplaintsRoute
  '/official/dashboard': typeof ProtectedOfficialDashboardRoute
  '/official/documents': typeof ProtectedOfficialDocumentsRoute
  '/official/reports': typeof ProtectedOfficialReportsRoute
  '/official/residents': typeof ProtectedOfficialResidentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/citizen': typeof ProtectedCitizenRouteWithChildren
  '/_protected/official': typeof ProtectedOfficialRouteWithChildren
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/admin/activity-logs': typeof ProtectedAdminActivityLogsRoute
  '/_protected/admin/analytics': typeof ProtectedAdminAnalyticsRoute
  '/_protected/admin/announcements': typeof ProtectedAdminAnnouncementsRoute
  '/_protected/admin/certificates': typeof ProtectedAdminCertificatesRoute
  '/_protected/admin/complaints': typeof ProtectedAdminComplaintsRoute
  '/_protected/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/_protected/admin/residents': typeof ProtectedAdminResidentsRoute
  '/_protected/admin/roles': typeof ProtectedAdminRolesRoute
  '/_protected/admin/settings': typeof ProtectedAdminSettingsRoute
  '/_protected/admin/users': typeof ProtectedAdminUsersRoute
  '/_protected/citizen/announcements': typeof ProtectedCitizenAnnouncementsRoute
  '/_protected/citizen/announcements-detailed': typeof ProtectedCitizenAnnouncementsDetailedRoute
  '/_protected/citizen/complaints': typeof ProtectedCitizenComplaintsRoute
  '/_protected/citizen/complaints-new': typeof ProtectedCitizenComplaintsNewRoute
  '/_protected/citizen/dashboard': typeof ProtectedCitizenDashboardRoute
  '/_protected/citizen/documents': typeof ProtectedCitizenDocumentsRoute
  '/_protected/citizen/documents-new': typeof ProtectedCitizenDocumentsNewRoute
  '/_protected/citizen/map': typeof ProtectedCitizenMapRoute
  '/_protected/citizen/profile': typeof ProtectedCitizenProfileRoute
  '/_protected/citizen/services': typeof ProtectedCitizenServicesRoute
  '/_protected/official/complaints': typeof ProtectedOfficialComplaintsRoute
  '/_protected/official/dashboard': typeof ProtectedOfficialDashboardRoute
  '/_protected/official/documents': typeof ProtectedOfficialDocumentsRoute
  '/_protected/official/reports': typeof ProtectedOfficialReportsRoute
  '/_protected/official/residents': typeof ProtectedOfficialResidentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/citizen'
    | '/official'
    | '/settings'
    | '/admin/activity-logs'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/certificates'
    | '/admin/complaints'
    | '/admin/dashboard'
    | '/admin/residents'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/citizen/announcements'
    | '/citizen/announcements-detailed'
    | '/citizen/complaints'
    | '/citizen/complaints-new'
    | '/citizen/dashboard'
    | '/citizen/documents'
    | '/citizen/documents-new'
    | '/citizen/map'
    | '/citizen/profile'
    | '/citizen/services'
    | '/official/complaints'
    | '/official/dashboard'
    | '/official/documents'
    | '/official/reports'
    | '/official/residents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/citizen'
    | '/official'
    | '/settings'
    | '/admin/activity-logs'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/certificates'
    | '/admin/complaints'
    | '/admin/dashboard'
    | '/admin/residents'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/citizen/announcements'
    | '/citizen/announcements-detailed'
    | '/citizen/complaints'
    | '/citizen/complaints-new'
    | '/citizen/dashboard'
    | '/citizen/documents'
    | '/citizen/documents-new'
    | '/citizen/map'
    | '/citizen/profile'
    | '/citizen/services'
    | '/official/complaints'
    | '/official/dashboard'
    | '/official/documents'
    | '/official/reports'
    | '/official/residents'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_protected/admin'
    | '/_protected/citizen'
    | '/_protected/official'
    | '/_protected/settings'
    | '/_protected/admin/activity-logs'
    | '/_protected/admin/analytics'
    | '/_protected/admin/announcements'
    | '/_protected/admin/certificates'
    | '/_protected/admin/complaints'
    | '/_protected/admin/dashboard'
    | '/_protected/admin/residents'
    | '/_protected/admin/roles'
    | '/_protected/admin/settings'
    | '/_protected/admin/users'
    | '/_protected/citizen/announcements'
    | '/_protected/citizen/announcements-detailed'
    | '/_protected/citizen/complaints'
    | '/_protected/citizen/complaints-new'
    | '/_protected/citizen/dashboard'
    | '/_protected/citizen/documents'
    | '/_protected/citizen/documents-new'
    | '/_protected/citizen/map'
    | '/_protected/citizen/profile'
    | '/_protected/citizen/services'
    | '/_protected/official/complaints'
    | '/_protected/official/dashboard'
    | '/_protected/official/documents'
    | '/_protected/official/reports'
    | '/_protected/official/residents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/official': {
      id: '/_protected/official'
      path: '/official'
      fullPath: '/official'
      preLoaderRoute: typeof ProtectedOfficialRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/citizen': {
      id: '/_protected/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof ProtectedCitizenRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/official/residents': {
      id: '/_protected/official/residents'
      path: '/residents'
      fullPath: '/official/residents'
      preLoaderRoute: typeof ProtectedOfficialResidentsRouteImport
      parentRoute: typeof ProtectedOfficialRoute
    }
    '/_protected/official/reports': {
      id: '/_protected/official/reports'
      path: '/reports'
      fullPath: '/official/reports'
      preLoaderRoute: typeof ProtectedOfficialReportsRouteImport
      parentRoute: typeof ProtectedOfficialRoute
    }
    '/_protected/official/documents': {
      id: '/_protected/official/documents'
      path: '/documents'
      fullPath: '/official/documents'
      preLoaderRoute: typeof ProtectedOfficialDocumentsRouteImport
      parentRoute: typeof ProtectedOfficialRoute
    }
    '/_protected/official/dashboard': {
      id: '/_protected/official/dashboard'
      path: '/dashboard'
      fullPath: '/official/dashboard'
      preLoaderRoute: typeof ProtectedOfficialDashboardRouteImport
      parentRoute: typeof ProtectedOfficialRoute
    }
    '/_protected/official/complaints': {
      id: '/_protected/official/complaints'
      path: '/complaints'
      fullPath: '/official/complaints'
      preLoaderRoute: typeof ProtectedOfficialComplaintsRouteImport
      parentRoute: typeof ProtectedOfficialRoute
    }
    '/_protected/citizen/services': {
      id: '/_protected/citizen/services'
      path: '/services'
      fullPath: '/citizen/services'
      preLoaderRoute: typeof ProtectedCitizenServicesRouteImport
      parentRoute: typeof ProtectedCitizenRoute
    }
    '/_protected/citizen/profile': {
      id: '/_protected/citizen/profile'
      path: '/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof ProtectedCitizenProfileRouteImport
      parentRoute: typeof ProtectedCitizenRoute
    }
    '/_protected/citizen/map': {
      id: '/_protected/citizen/map'
      path: '/map'
      fullPath: '/citizen/map'
      preLoaderRoute: typeof ProtectedCitizenMapRouteImport
      parentRoute: typeof ProtectedCitizenRoute
    }
    '/_protected/citizen/documents-new': {
      id: '/_protected/citizen/documents-new'
      path: '/documents-new'
      fullPath: '/citizen/documents-new'
      preLoaderRoute: typeof ProtectedCitizenDocumentsNewRouteImport
      parentRoute: typeof ProtectedCitizenRoute
    }
    '/_protected/citizen/documents': {
      id: '/_protected/citizen/documents'
      path: '/documents'
      fullPath: '/citizen/documents'
      preLoaderRoute: typeof ProtectedCitizenDocumentsRouteImport
      parentRoute: typeof ProtectedCitizenRoute
    }
    '/_protected/citizen/dashboard': {
      id: '/_protected/citizen/dashboard'
      path: '/dashboard'
      fullPath: '/citizen/dashboard'
      preLoaderRoute: typeof ProtectedCitizenDashboardRouteImport
      parentRoute: typeof ProtectedCitizenRoute
    }
    '/_protected/citizen/complaints-new': {
      id: '/_protected/citizen/complaints-new'
      path: '/complaints-new'
      fullPath: '/citizen/complaints-new'
      preLoaderRoute: typeof ProtectedCitizenComplaintsNewRouteImport
      parentRoute: typeof ProtectedCitizenRoute
    }
    '/_protected/citizen/complaints': {
      id: '/_protected/citizen/complaints'
      path: '/complaints'
      fullPath: '/citizen/complaints'
      preLoaderRoute: typeof ProtectedCitizenComplaintsRouteImport
      parentRoute: typeof ProtectedCitizenRoute
    }
    '/_protected/citizen/announcements-detailed': {
      id: '/_protected/citizen/announcements-detailed'
      path: '/announcements-detailed'
      fullPath: '/citizen/announcements-detailed'
      preLoaderRoute: typeof ProtectedCitizenAnnouncementsDetailedRouteImport
      parentRoute: typeof ProtectedCitizenRoute
    }
    '/_protected/citizen/announcements': {
      id: '/_protected/citizen/announcements'
      path: '/announcements'
      fullPath: '/citizen/announcements'
      preLoaderRoute: typeof ProtectedCitizenAnnouncementsRouteImport
      parentRoute: typeof ProtectedCitizenRoute
    }
    '/_protected/admin/users': {
      id: '/_protected/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminUsersRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/settings': {
      id: '/_protected/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof ProtectedAdminSettingsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/roles': {
      id: '/_protected/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof ProtectedAdminRolesRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/residents': {
      id: '/_protected/admin/residents'
      path: '/residents'
      fullPath: '/admin/residents'
      preLoaderRoute: typeof ProtectedAdminResidentsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/dashboard': {
      id: '/_protected/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof ProtectedAdminDashboardRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/complaints': {
      id: '/_protected/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof ProtectedAdminComplaintsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/certificates': {
      id: '/_protected/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof ProtectedAdminCertificatesRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/announcements': {
      id: '/_protected/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof ProtectedAdminAnnouncementsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/analytics': {
      id: '/_protected/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof ProtectedAdminAnalyticsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/activity-logs': {
      id: '/_protected/admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof ProtectedAdminActivityLogsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
  }
}

interface ProtectedAdminRouteChildren {
  ProtectedAdminActivityLogsRoute: typeof ProtectedAdminActivityLogsRoute
  ProtectedAdminAnalyticsRoute: typeof ProtectedAdminAnalyticsRoute
  ProtectedAdminAnnouncementsRoute: typeof ProtectedAdminAnnouncementsRoute
  ProtectedAdminCertificatesRoute: typeof ProtectedAdminCertificatesRoute
  ProtectedAdminComplaintsRoute: typeof ProtectedAdminComplaintsRoute
  ProtectedAdminDashboardRoute: typeof ProtectedAdminDashboardRoute
  ProtectedAdminResidentsRoute: typeof ProtectedAdminResidentsRoute
  ProtectedAdminRolesRoute: typeof ProtectedAdminRolesRoute
  ProtectedAdminSettingsRoute: typeof ProtectedAdminSettingsRoute
  ProtectedAdminUsersRoute: typeof ProtectedAdminUsersRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminActivityLogsRoute: ProtectedAdminActivityLogsRoute,
  ProtectedAdminAnalyticsRoute: ProtectedAdminAnalyticsRoute,
  ProtectedAdminAnnouncementsRoute: ProtectedAdminAnnouncementsRoute,
  ProtectedAdminCertificatesRoute: ProtectedAdminCertificatesRoute,
  ProtectedAdminComplaintsRoute: ProtectedAdminComplaintsRoute,
  ProtectedAdminDashboardRoute: ProtectedAdminDashboardRoute,
  ProtectedAdminResidentsRoute: ProtectedAdminResidentsRoute,
  ProtectedAdminRolesRoute: ProtectedAdminRolesRoute,
  ProtectedAdminSettingsRoute: ProtectedAdminSettingsRoute,
  ProtectedAdminUsersRoute: ProtectedAdminUsersRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedCitizenRouteChildren {
  ProtectedCitizenAnnouncementsRoute: typeof ProtectedCitizenAnnouncementsRoute
  ProtectedCitizenAnnouncementsDetailedRoute: typeof ProtectedCitizenAnnouncementsDetailedRoute
  ProtectedCitizenComplaintsRoute: typeof ProtectedCitizenComplaintsRoute
  ProtectedCitizenComplaintsNewRoute: typeof ProtectedCitizenComplaintsNewRoute
  ProtectedCitizenDashboardRoute: typeof ProtectedCitizenDashboardRoute
  ProtectedCitizenDocumentsRoute: typeof ProtectedCitizenDocumentsRoute
  ProtectedCitizenDocumentsNewRoute: typeof ProtectedCitizenDocumentsNewRoute
  ProtectedCitizenMapRoute: typeof ProtectedCitizenMapRoute
  ProtectedCitizenProfileRoute: typeof ProtectedCitizenProfileRoute
  ProtectedCitizenServicesRoute: typeof ProtectedCitizenServicesRoute
}

const ProtectedCitizenRouteChildren: ProtectedCitizenRouteChildren = {
  ProtectedCitizenAnnouncementsRoute: ProtectedCitizenAnnouncementsRoute,
  ProtectedCitizenAnnouncementsDetailedRoute:
    ProtectedCitizenAnnouncementsDetailedRoute,
  ProtectedCitizenComplaintsRoute: ProtectedCitizenComplaintsRoute,
  ProtectedCitizenComplaintsNewRoute: ProtectedCitizenComplaintsNewRoute,
  ProtectedCitizenDashboardRoute: ProtectedCitizenDashboardRoute,
  ProtectedCitizenDocumentsRoute: ProtectedCitizenDocumentsRoute,
  ProtectedCitizenDocumentsNewRoute: ProtectedCitizenDocumentsNewRoute,
  ProtectedCitizenMapRoute: ProtectedCitizenMapRoute,
  ProtectedCitizenProfileRoute: ProtectedCitizenProfileRoute,
  ProtectedCitizenServicesRoute: ProtectedCitizenServicesRoute,
}

const ProtectedCitizenRouteWithChildren =
  ProtectedCitizenRoute._addFileChildren(ProtectedCitizenRouteChildren)

interface ProtectedOfficialRouteChildren {
  ProtectedOfficialComplaintsRoute: typeof ProtectedOfficialComplaintsRoute
  ProtectedOfficialDashboardRoute: typeof ProtectedOfficialDashboardRoute
  ProtectedOfficialDocumentsRoute: typeof ProtectedOfficialDocumentsRoute
  ProtectedOfficialReportsRoute: typeof ProtectedOfficialReportsRoute
  ProtectedOfficialResidentsRoute: typeof ProtectedOfficialResidentsRoute
}

const ProtectedOfficialRouteChildren: ProtectedOfficialRouteChildren = {
  ProtectedOfficialComplaintsRoute: ProtectedOfficialComplaintsRoute,
  ProtectedOfficialDashboardRoute: ProtectedOfficialDashboardRoute,
  ProtectedOfficialDocumentsRoute: ProtectedOfficialDocumentsRoute,
  ProtectedOfficialReportsRoute: ProtectedOfficialReportsRoute,
  ProtectedOfficialResidentsRoute: ProtectedOfficialResidentsRoute,
}

const ProtectedOfficialRouteWithChildren =
  ProtectedOfficialRoute._addFileChildren(ProtectedOfficialRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedCitizenRoute: typeof ProtectedCitizenRouteWithChildren
  ProtectedOfficialRoute: typeof ProtectedOfficialRouteWithChildren
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedCitizenRoute: ProtectedCitizenRouteWithChildren,
  ProtectedOfficialRoute: ProtectedOfficialRouteWithChildren,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
